spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: younes
    password: younes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
